export ZSH="$HOME/.oh-my-zsh"
export UTILS="$HOME/.utils"

eval $(thefuck --alias)

ZSH_THEME="agnoster"

plugins=(
    git
    kubectl
    mvn
    zsh-autosuggestions
    docker
    docker-compose
    aws
    helm
    thefuck
    zsh-syntax-highlighting
    colored-man-pages
    extract
    z
)

source $ZSH/oh-my-zsh.sh

for f in $UTILS/*; do source $f; done
